name: bookmyvilla

services:
  backend:
    build: ./backend
    container_name: bookmyvilla-backend
    ports:
      - "5001:5001"
    env_file:
      - path: ./backend/.env
        required: false
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bookmyvilla-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: bookmyvilla-admin
    ports:
      - "5174:5174"
    depends_on:
      - backend

  owner:
    build: ./owner
    container_name: bookmyvilla-owner
    ports:
      - "5175:5175"
    depends_on:
      - backend

  caretaker:
    build: ./caretaker
    container_name: bookmyvilla-caretaker
    ports:
      - "5176:5176"
    depends_on:
      - backend
