apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app.kubernetes.io/name: search-service
    app.kubernetes.io/part-of: bookmyvilla
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: search-service
  ports:
    - name: http
      port: 2109
      targetPort: http
