import { createContext, lazy, Suspense, useCallback, useContext, useEffect, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { login, manager, propertyService, session } from './services/api';
import { Badge, Empty, Field, guest, Icon, label, date } from './ui';
const Operations = lazy(() => import('./Operations'));
const PropertyPage = lazy(() => import('./PropertyPage'));
const Queues = lazy(() => import('./Queues'));
const Bookings = lazy(() => import('./Bookings'));
const Context = createContext(null);
export const usePanel = () => useContext(Context);
export function useData(loader, key) {
  const [state, setState] = useState({ data: null, loading: true, error: '' }); const [revision, setRevision] = useState(0);
  useEffect(() => { let live = true; setState({ data: null, loading: true, error: '' }); Promise.resolve().then(loader).then(data => { if (live) setState({ data, loading: false, error: '' }); }).catch(err => { if (live) setState({ data: null, loading: false, error: err.message }); }); return () => { live = false; }; }, [key, revision]); // Each key identifies the full server scope.
  return { ...state, reload: () => setRevision(v => v + 1) };
}
export function Result({ state, children }) { return state.loading ? <p className="loading" role="status">Loading operations…</p> : state.error ? <div className="error" role="alert"><strong>{state.error}</strong><button onClick={state.reload}>Retry</button></div> : children; }
const navigation = [['dashboard', 'Dashboard', 'grid'], ['today', 'Today', 'calendar'], ['properties', 'Managed properties', 'home'], ['bookings', 'Bookings', 'list'], ['calendar', 'Calendar', 'calendar'], ['guests', 'Guests', 'people'], ['housekeeping', 'Housekeeping', 'check'], ['requests', 'Guest requests', 'list'], ['complaints', 'Complaints', 'shield'], ['maintenance', 'Maintenance', 'tools'], ['inventory', 'Inventory', 'box'], ['tasks', 'Tasks', 'check'], ['damage', 'Damage reports', 'shield'], ['expenses', 'Expenses', 'list'], ['reports', 'Reports', 'grid'], ['notifications', 'Notifications', 'bell'], ['profile', 'Profile', 'people']];
function Login({ signedIn }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { signedIn(await login(email, password)); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="login-page"><main className="login"><Link className="brand" to="/login"><Icon name="home"/><strong>BookMyVilla</strong></Link><h1>Villa Manager sign in</h1><p>Run daily operations across your assigned properties.</p><form onSubmit={submit}>{error && <p className="error" role="alert">{error}</p>}<Field label="Work email" type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required/><Field label="Password" type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required/><button className="primary" disabled={busy}>{busy ? 'Signing in…' : 'Open operations'}<Icon name="arrow"/></button></form><p className="login-foot">Use the Villa Manager account provided by BookMyVilla Admin.</p></main></div>;
}
export default function App() {
  const [auth, setAuth] = useState(null); const [booting, setBooting] = useState(!!session.get()); const [bootError, setBootError] = useState('');
  const navigate = useNavigate();
  const verify = useCallback(async () => { try { const next = await manager('/session'); setAuth(next); setBootError(''); } catch (err) { if ([401, 403].includes(err.status)) { session.clear(); setAuth(null); } else setBootError(err.message); } finally { setBooting(false); } }, []);
  useEffect(() => { if (session.get()) verify(); }, [verify]);
  useEffect(() => { if (!auth) return; const timer = setInterval(verify, 30000); const visible = () => { if (!document.hidden) verify(); }; document.addEventListener('visibilitychange', visible); return () => { clearInterval(timer); document.removeEventListener('visibilitychange', visible); }; }, [!!auth, verify]);
  function logout() { session.clear(); setAuth(null); navigate('/login', { replace: true }); }
  if (booting) return <div className="boot" role="status">Checking Villa Manager access…</div>;
  if (!auth && bootError) return <div className="boot"><p role="alert">{bootError}</p><button onClick={verify}>Retry connection</button><button onClick={logout}>Back to sign in</button></div>;
  if (!auth) return <Routes><Route path="/login" element={<Login signedIn={value => { setAuth(value); navigate('/today', { replace: true }); }}/>}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>;
  return <Shell auth={auth} logout={logout} warning={bootError}/>;
}
function Shell({ auth, logout, warning }) {
  const [params, setParams] = useSearchParams();
  const [owner, setOwner] = useState(''); const [switchSearch, setSwitchSearch] = useState(''); const [switchPage, setSwitchPage] = useState(1); const [menu, setMenu] = useState(false);
  const location = useLocation(); const navigate = useNavigate(); const current = navigation.find(([key]) => location.pathname.startsWith('/' + key));
  const propertyId = location.pathname.match(/^\/properties\/([a-f0-9]{24})$/i)?.[1] || params.get('propertyId') || 'all';
  const owners = useData(propertyService.owners, 'owners'); const properties = useData(() => propertyService.list({ owner, q: switchSearch, page: switchPage, limit: 50 }), 'switch:' + owner + ':' + switchSearch + ':' + switchPage);
  const selected = useData(() => propertyId === 'all' ? Promise.resolve(null) : propertyService.get(propertyId), 'selected:' + propertyId);
  function select(value) { setMenu(false); if (/^\/(properties|bookings)\//.test(location.pathname)) navigate('/today?' + (value !== 'all' ? 'propertyId=' + value : '')); else setParams(value === 'all' ? {} : { propertyId: value }); }
  const href = path => path + (propertyId !== 'all' ? '?propertyId=' + propertyId : '');
  useEffect(() => { setMenu(false); }, [location.pathname]);
  return <Context.Provider value={{ ...auth, propertyId, selected: selected.data, href, refreshProperty: selected.reload }}><div className="shell">
    {menu && <button className="nav-scrim" aria-label="Close navigation" onClick={() => setMenu(false)}/>}
    <aside className={'sidebar' + (menu ? ' open' : '')}><Link className="brand" to={href('/today')}><Icon name="home"/><span><strong>BookMyVilla</strong><small>Villa Manager</small></span></Link><nav aria-label="Operations navigation">{navigation.map(([key, title, icon]) => <NavLink key={key} to={href('/' + key)} onClick={() => setMenu(false)}><Icon name={icon}/>{title}</NavLink>)}</nav><div className="sidebar-foot"><strong>{auth.user.name}</strong><small>Villa Manager</small><button onClick={logout}><Icon name="exit"/>Sign out</button></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu icon-btn" aria-label="Open navigation" aria-expanded={menu} onClick={() => setMenu(true)}><Icon name="menu"/></button><strong>{current?.[1] || 'Operations'}</strong><span className="date">{date(new Date())} · IST</span><Link className="icon-btn" aria-label="Operational notifications" to={href('/notifications')}><Icon name="bell"/></Link></header>
      <section className="switcher" aria-label="Property scope"><Field label="Owner"><select value={owner} onChange={e => { setOwner(e.target.value); setSwitchPage(1); select('all'); }}><option value="">All assigned owners</option>{owners.data?.map(o => <option key={o._id} value={o._id}>{o.name}</option>)}</select></Field><Field label="Find property" type="search" placeholder="Search assigned properties" value={switchSearch} onChange={e => { setSwitchSearch(e.target.value); setSwitchPage(1); }}/><Field label="Working property"><select value={propertyId} disabled={properties.loading} onChange={e => select(e.target.value)}><option value="all">All assigned properties</option>{selected.data && !properties.data?.items.some(p => p._id === propertyId) && <option value={propertyId}>{selected.data.property.name}</option>}{properties.data?.items.map(p => <option key={p._id} value={p._id}>{p.name} · {p.owner?.name}</option>)}</select></Field>{properties.data?.total > 50 && <div className="switch-pages"><button disabled={switchPage <= 1} onClick={() => setSwitchPage(p => p - 1)}>Previous 50</button><button disabled={switchPage * 50 >= properties.data.total} onClick={() => setSwitchPage(p => p + 1)}>Next 50</button></div>}<span className="scope-note"><Icon name="shield"/>Assigned managed properties</span></section>
      <div className="content">{warning && <p className="error" role="alert">{warning}</p>}{(properties.error || owners.error) && <p className="error" role="alert">{properties.error || owners.error}<button onClick={() => { properties.reload(); owners.reload(); }}>Retry switcher</button></p>}{selected.error ? <div className="error" role="alert">{selected.error}<button onClick={() => select('all')}>Return to assigned properties</button></div> : <Suspense fallback={<p role="status">Loading view…</p>}><Routes><Route path="/login" element={<Navigate to="/today" replace/>}/><Route path="/dashboard" element={<Operations mode="dashboard"/>}/><Route path="/today" element={<Operations mode="today"/>}/><Route path="/notifications" element={<Operations mode="notifications"/>}/><Route path="/properties" element={<PropertyPage/>}/><Route path="/properties/:id" element={<PropertyPage/>}/><Route path="/calendar" element={<PropertyPage calendar/>}/><Route path="/bookings" element={<Bookings/>}/><Route path="/bookings/:id" element={<Bookings/>}/>{['guests', 'housekeeping', 'requests', 'complaints', 'maintenance', 'inventory', 'tasks', 'damage', 'expenses', 'reports'].map(kind => <Route key={kind} path={'/' + kind} element={kind === 'guests' ? <Bookings guestsOnly/> : <Queues kind={kind}/>}/>)}<Route path="/profile" element={<Profile/>}/><Route path="/" element={<Navigate to="/today" replace/>}/><Route path="*" element={<Empty title="Page not found"><Link to={href('/today')}>Open Today operations</Link></Empty>}/></Routes></Suspense>}</div>
    </main></div></Context.Provider>;
}
function Profile() { const { user } = usePanel(); return <><div className="page-head"><h1>Your profile</h1><p>Your operational account is managed by BookMyVilla Admin.</p></div><section className="panel"><dl className="details"><dt>Name</dt><dd>{user.name}</dd><dt>Email</dt><dd>{user.email}</dd><dt>Phone</dt><dd>{user.phone || 'Not provided'}</dd><dt>Role</dt><dd><Badge value={user.role}/></dd><dt>Account status</dt><dd><Badge value={user.status}/></dd></dl></section></>; }
