import { useCallback, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Result, useData, usePanel } from './App';
import GuideAssignment from './GuideAssignment';
import { bookingService, manager, query, taskService } from './services/api';
import { Badge, date, Drawer, Empty, Field, guest, money, Pager, Table, today } from './ui';
export default function Bookings({ guestsOnly = false }) {
  const { id } = useParams(); const { propertyId, href } = usePanel(); const navigate = useNavigate(); const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [view, setView] = useState('');
  const state = useData(() => manager('/resources/' + (guestsOnly ? 'guests' : 'bookings') + '?' + query({ propertyId, page, status, q: search, today: view })), 'bookings:' + propertyId + ':' + page + ':' + search + ':' + status + ':' + view + ':' + guestsOnly);
  const close = useCallback(() => navigate(href('/bookings')), [navigate, href]);
  return <><div className="page-head"><div><h1>{guestsOnly ? 'In-house guests' : 'Bookings'}</h1><p>{guestsOnly ? 'Guests currently staying at your assigned properties.' : 'Prepare arrivals, assign rooms and record guest departures.'}</p></div><button onClick={state.reload}>Refresh bookings</button></div><section className="panel"><div className="filters"><Field label="Guest / booking search" type="search" placeholder="Name, phone or booking ID" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/>{!guestsOnly && <><Field label="Booking status"><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}>{['', 'confirmed', 'pending', 'cancelled'].map(s => <option key={s} value={s}>{s || 'All statuses'}</option>)}</select></Field><Field label="Daily view"><select value={view} onChange={e => { setView(e.target.value); setPage(1); }}><option value="">All bookings</option><option value="arrivals">Arrivals today</option><option value="departures">Departures due</option></select></Field></>}</div><Result state={state}>{state.data && (state.data.items.length ? <><Table headings={['Guest / booking', 'Property / room', 'Stay dates', 'Guests', 'Arrival / requests', 'Payment', 'Stay status', 'Action']}>{state.data.items.map(b => <tr key={b._id}><td><Link to={href('/bookings/' + b._id)} className="row-link">{guest(b)}</Link><small>#{b._id.slice(-8)}</small></td><td>{b.property?.name}<small>{b.room?.number || 'Unassigned'}</small></td><td>{date(b.checkIn)} – {date(b.checkOut)}</td><td>{b.operations?.actualGuests || b.guests}</td><td>{b.guestDetails?.arrivalTime || 'Not supplied'}<small>{b.guestDetails?.specialRequests || 'No special requests'}</small>{b.guide?.requested && <small><strong>Guide needed · {b.guide.days} day{b.guide.days === 1 ? '' : 's'}</strong></small>}</td><td><Badge value={b.paymentStatus}/></td><td><Badge value={b.status === 'confirmed' ? b.stayStatus : b.status}/></td><td><Link to={href('/bookings/' + b._id)}>Open booking</Link></td></tr>)}</Table><Pager data={state.data} setPage={setPage}/></> : <Empty title="No matching bookings">New customer bookings for your assigned properties appear automatically.</Empty>)}</Result></section>{id && <Drawer title="Booking operations" close={close}><BookingDetail key={id} id={id} onSaved={state.reload}/></Drawer>}</>;
}
function BookingDetail({ id, onSaved }) {
  const state = useData(() => bookingService.get(id), 'booking:' + id); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function perform(fn) { setBusy(true); setMessage(''); setError(''); try { const result = await fn(); setMessage(result?.warning || 'Booking updated.'); state.reload(); onSaved(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <><Result state={state}>{state.data && <><div className="detail-intro"><h3>{guest(state.data)}</h3><p>{state.data.property?.name} · {state.data.room?.number || 'Room unassigned'}</p><Badge value={state.data.stayStatus}/></div><dl className="details"><dt>Booking</dt><dd className="reference">{state.data._id}</dd><dt>Dates</dt><dd>{date(state.data.checkIn)} – {date(state.data.checkOut)}</dd><dt>Booked guests</dt><dd>{state.data.guests}</dd><dt>Guest contact</dt><dd>{state.data.guest?.phone || state.data.user?.phone || 'Not provided'}</dd><dt>Booking payment</dt><dd><Badge value={state.data.paymentStatus}/></dd><dt>Security deposit</dt><dd>{money(state.data.securityDepositAmount)} · {state.data.operations?.depositVerified ? 'Verified' : 'Not verified'}</dd><dt>ID verification</dt><dd>{state.data.operations?.idVerified ? 'Verified' : 'Not verified'}</dd><dt>Special requests</dt><dd>{state.data.guestDetails?.specialRequests || 'None supplied'}</dd><dt>Extra guest requirement</dt><dd>{money(state.data.operations?.extraGuestAmount)} · <Badge value={state.data.operations?.extraGuestPaymentStatus || 'not_required'}/></dd></dl>
    {state.data.status === 'confirmed' && state.data.stayStatus !== 'checked_out' && <><GuestForm booking={state.data} busy={busy} perform={perform}/><RoomAssignment booking={state.data} busy={busy} perform={perform}/><section className="detail-section"><h3>Stay actions</h3>{state.data.stayStatus === 'in_house' ? <button className="primary" disabled={busy} onClick={() => perform(() => bookingService.stay(id, 'check-out'))}>Confirm checkout & create cleaning task</button> : <button className="primary" disabled={busy} onClick={() => perform(() => bookingService.stay(id, 'check-in'))}>Confirm check-in</button>}<p className="help">Check-in requires verified guest ID, applicable deposit, paid booking and a ready room. Checkout starts cleaning and inspection.</p><StayChange booking={state.data} busy={busy} perform={perform}/></section></>}
    {state.data.guide?.requested && state.data.status === 'confirmed' && state.data.stayStatus !== 'checked_out' && <GuideAssignment key={state.data.guide.assigned?._id || 'unassigned-guide'} booking={state.data} onSaved={() => { state.reload(); onSaved(); }} />}
    <section className="detail-section"><h3>Activity</h3>{state.data.actionHistory?.slice(-8).reverse().map((a, i) => <div className="activity" key={i}><strong>{a.action}</strong><p>{a.reason}</p><small>{date(a.timestamp)} · {a.performedBy}</small></div>)}</section>
  </>}</Result>{error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}</>;
}
function GuestForm({ booking, perform, busy }) {
  const [form, setForm] = useState({ arrivalTime: booking.guestDetails?.arrivalTime || '', actualGuests: booking.operations?.actualGuests || booking.guests, internalNote: booking.operations?.internalNote || '', idVerified: !!booking.operations?.idVerified, depositVerified: !!booking.operations?.depositVerified });
  return <form className="detail-section form-stack" onSubmit={e => { e.preventDefault(); perform(() => bookingService.details(booking._id, form)); }}><h3>Confirm guest details</h3><div className="form-grid"><Field label="Arrival information" maxLength="40" placeholder="e.g. 2:30 PM" value={form.arrivalTime} onChange={e => setForm(f => ({ ...f, arrivalTime: e.target.value }))}/><Field label="Actual guest count" type="number" min="1" max={booking.room?.capacity || 50} required value={form.actualGuests} onChange={e => setForm(f => ({ ...f, actualGuests: e.target.value }))}/></div><Field label="Internal operational note"><textarea maxLength="500" value={form.internalNote} onChange={e => setForm(f => ({ ...f, internalNote: e.target.value }))}/></Field><label className="checkbox"><input type="checkbox" checked={form.idVerified} onChange={e => setForm(f => ({ ...f, idVerified: e.target.checked }))}/>Guest identity checked in person</label><label className="checkbox"><input type="checkbox" checked={form.depositVerified} onChange={e => setForm(f => ({ ...f, depositVerified: e.target.checked }))}/>Applicable security deposit verified</label><p className="help">Extra guests are capacity-checked and charged by the backend. Pending charges require finance review.</p><button disabled={busy}>{busy ? 'Saving…' : 'Save guest details'}</button></form>;
}
function RoomAssignment({ booking, perform, busy }) {
  const alternatives = useData(() => bookingService.alternatives(booking._id), 'alternatives:' + booking._id + ':' + booking.room?._id); const [room, setRoom] = useState(''); const [reason, setReason] = useState('');
  return <form className="detail-section form-stack" onSubmit={e => { e.preventDefault(); perform(() => bookingService.assign(booking._id, room, reason, !!booking.room)); }}><h3>{booking.room ? 'Change assigned room' : 'Assign a room'}</h3><Result state={alternatives}>{alternatives.data && <><Field label="Compatible available room"><select required value={room} onChange={e => setRoom(e.target.value)}><option value="">{alternatives.data.length ? 'Choose room' : 'No compatible rooms available'}</option>{alternatives.data.map(r => <option key={r._id} value={r._id}>{r.number} · {r.type} · capacity {r.capacity}</option>)}</select></Field>{booking.room && <Field label="Reassignment reason" required maxLength="200" value={reason} onChange={e => setReason(e.target.value)}/>}<button disabled={busy || !room}>{booking.room ? 'Reassign & record reason' : 'Assign room'}</button></>}</Result></form>;
}
function StayChange({ booking, busy, perform }) {
  const [kind, setKind] = useState('late_checkout'); const [notes, setNotes] = useState(''); const [assessment, setAssessment] = useState(null); const [newCheckout, setNewCheckout] = useState('');
  return <form className="form-stack" onSubmit={e => { e.preventDefault(); perform(async () => { const result = await manager('/bookings/' + booking._id + '/stay-change-check?' + query({ kind, newCheckout })); setAssessment(result); if (result.conflict) throw new Error(result.message); return taskService.create({ propertyId: booking.property._id, roomId: booking.room?._id, bookingId: booking._id, kind: 'stay_change', title: kind.replace(/_/g, ' ') + ' review', category: kind, notes: notes + (newCheckout ? ' · Requested checkout ' + newCheckout : ''), dueDate: today() }); }); }}><h4>Early arrival / late checkout / extension</h4><Field label="Request type"><select value={kind} onChange={e => { setKind(e.target.value); setAssessment(null); }}>{['early_checkin', 'late_checkout', 'extend_stay'].map(k => <option key={k} value={k}>{k.replace(/_/g, ' ')}</option>)}</select></Field>{kind === 'extend_stay' && <Field label="Requested checkout" type="date" required value={newCheckout} onChange={e => setNewCheckout(e.target.value)}/>}<Field label="Request details" required maxLength="500" value={notes} onChange={e => setNotes(e.target.value)}/><button disabled={busy}>Check availability & request review</button>{assessment && <p className="help">{assessment.message}</p>}<p className="help">Stay changes need policy and charge approval. This request does not change booked dates or authorize a free or paid stay change.</p></form>;
}
