import { Link } from 'react-router-dom';
import { useData, usePanel, Result } from './App';
import { manager } from './services/api';
import { Badge, date, Empty, guest, Icon } from './ui';
export default function Operations({ mode }) {
  const { propertyId, href } = usePanel(); const state = useData(() => manager('/dashboard?propertyId=' + propertyId), 'dashboard:' + propertyId + ':' + mode);
  const title = mode === 'today' ? 'Today operations' : mode === 'notifications' ? 'Operational notifications' : 'Operations dashboard';
  return <><div className="page-head"><div><h1>{title}</h1><p>{mode === 'notifications' ? 'Current booking, guest and readiness alerts across your assigned properties.' : 'Keep arrivals moving, rooms ready and guest issues in view.'}</p></div><button onClick={state.reload}>Refresh operations</button></div><Result state={state}>{state.data && <>
    {mode !== 'notifications' && <div className={'stats ' + (mode === 'today' ? 'today-stats' : '')}>{Object.entries(state.data.summary).filter(([k]) => !['roomCount', 'tasks'].includes(k) && (mode !== 'today' || !['managedOwners', 'managedProperties'].includes(k))).map(([key, value]) => <Link key={key} to={href('/' + ({ managedOwners: 'properties', managedProperties: 'properties', arrivals: 'bookings', departures: 'bookings', activeGuests: 'guests', cleaning: 'housekeeping', complaints: 'complaints', requests: 'requests', maintenance: 'maintenance', roomsNotReady: 'properties' }[key]))}><span>{{ managedOwners: 'Managed owners', managedProperties: 'Managed properties', arrivals: 'Today’s arrivals', departures: 'Departures due', activeGuests: 'In-house guests', cleaning: 'Pending cleaning', complaints: 'Open complaints', requests: 'Guest requests', maintenance: 'Maintenance issues', roomsNotReady: 'Rooms not ready' }[key]}</span><strong>{value}</strong></Link>)}</div>}
    <section className="panel attention"><div className="section-head"><div><h2>{mode === 'notifications' ? 'Current alerts' : 'Needs attention'}</h2><p>Live open work. Select an item to act on it.</p></div><Badge value="operations"/></div>
      {!state.data.attention.bookings.length && !state.data.attention.requests.length && !state.data.attention.housekeeping.length && !state.data.attention.tasks?.length && !state.data.attention.rooms?.length ? <Empty title="All clear for now">No open arrival, guest or cleaning alerts in this scope.</Empty> : <div className="attention-list">
        {state.data.attention.requests.map(r => <Link className="attention-row" key={r._id} to={href('/' + (r.kind === 'issue' ? 'complaints' : 'requests'))}><Icon name={r.kind === 'issue' ? 'shield' : 'list'}/><div><strong>{r.code} · {r.category.replace(/_/g, ' ')}</strong><p>{r.property?.name} · {r.description}</p></div><Badge value={r.status}/><Icon name="arrow"/></Link>)}
        {state.data.attention.bookings.map(b => <Link className="attention-row" key={b._id} to={href('/bookings/' + b._id)}><Icon name="calendar"/><div><strong>{guest(b)} · {b.stayStatus === 'in_house' ? 'Checkout due' : 'Arrival due'}</strong><p>{b.property?.name} · {b.room?.number || 'Room not assigned'} · {date(b.stayStatus === 'in_house' ? b.checkOut : b.checkIn)}{b.guestDetails?.arrivalTime ? ' · ' + b.guestDetails.arrivalTime : ''}</p></div><Badge value={b.stayStatus}/><Icon name="arrow"/></Link>)}
        {state.data.attention.housekeeping.map(t => <Link className="attention-row" key={t._id} to={href('/housekeeping')}><Icon name="check"/><div><strong>{t.room?.number} · {t.title}</strong><p>{t.property?.name} · Due {date(t.dueDate)}</p></div><Badge value={t.stage}/><Icon name="arrow"/></Link>)}
        {state.data.attention.tasks?.map(t => <Link className="attention-row" key={t._id} to={href(t.kind === 'maintenance' ? '/maintenance' : '/tasks')}><Icon name="tools"/><div><strong>{t.title}</strong><p>{t.property?.name} · {t.room?.number || 'Property-wide'} · Due {date(t.dueDate)}</p></div><Badge value={t.status}/><Icon name="arrow"/></Link>)}
        {state.data.attention.rooms?.map(r => <Link className="attention-row" key={'room-' + r._id} to={href('/properties/' + r.property?._id)}><Icon name="home"/><div><strong>{r.number} · Room not ready</strong><p>{r.property?.name} · {r.name}</p></div><Badge value={r.readinessStatus}/><Icon name="arrow"/></Link>)}
      </div>}
    </section>
    {mode === 'notifications' && state.data.attention.notifications?.bookings?.length > 0 && <section className="panel"><h2>Booking and arrival updates</h2>{state.data.attention.notifications.bookings.map(b => <Link className="attention-row" key={b._id} to={href('/bookings/' + b._id)}><Icon name="calendar"/><div><strong>{guest(b)} ? {b.status === 'cancelled' ? 'Booking cancelled' : b.paymentStatus === 'pending' ? 'Payment pending' : b.guestDetails?.arrivalTime ? 'Arrival updated: ' + b.guestDetails.arrivalTime : 'Booking received'}</strong><p>{b.property?.name} ? {date(b.checkIn)} ? {date(b.checkOut)}</p></div><Icon name="arrow"/></Link>)}</section>}
    {mode === 'notifications' && <section className="panel"><h2>New confirmed bookings · Last 24 hours</h2>{state.data.attention.recentBookings?.length ? state.data.attention.recentBookings.map(b => <Link className="attention-row" key={b._id} to={href('/bookings/' + b._id)}><Icon name="calendar"/><div><strong>{guest(b)} · #{b._id.slice(-8)}</strong><p>{b.property?.name} · {date(b.checkIn)} – {date(b.checkOut)}</p></div><Icon name="arrow"/></Link>) : <Empty title="No new confirmed bookings"/>}</section>}
    {mode !== 'notifications' && <div className="daily-links">{[['Arrivals & departures', '/bookings', 'calendar'], ['In-house guests', '/guests', 'people'], ['Rooms & readiness', '/properties', 'home'], ['Maintenance & tasks', '/maintenance', 'tools'], ['Cleaning & inspection', '/housekeeping', 'check'], ['Guest requests', '/requests', 'list']].map(([title, path, icon]) => <Link key={path} to={href(path)}><Icon name={icon}/>{title}<Icon name="arrow"/></Link>)}</div>}
  </>}</Result></>;
}
