import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Result, useData, usePanel } from './App';
import { api, availabilityService, manager, propertyService, query } from './services/api';
import { Badge, date, Empty, Field, money, nextDay, Pager, Table, today } from './ui';
export default function PropertyPage({ calendar = false }) {
  const { id } = useParams(); const { propertyId } = usePanel();
  if (calendar) return propertyId === 'all' ? <Empty title="Select a working property">Choose a property above to view its room calendar and manage blocks.</Empty> : <Calendar id={propertyId}/>;
  return id ? <PropertyDetail key={id} id={id}/> : <PropertyList/>;
}
function PropertyList() {
  const { propertyId, href } = usePanel(); const [filters, setFilters] = useState({ q: '', owner: '', type: '', location: '', operationalStatus: '', arrivals: '', issues: '' }); const [page, setPage] = useState(1);
  const owners = useData(propertyService.owners, 'list-owners'); const state = useData(() => propertyService.list({ ...filters, page, propertyId }), 'properties:' + query(filters) + ':' + page + ':' + propertyId);
  function change(key, value) { setPage(1); setFilters(f => ({ ...f, [key]: value })); }
  return <><div className="page-head"><div><h1>Managed properties</h1><p>Occupancy, arrivals and operational readiness across your portfolio.</p></div><button onClick={state.reload}>Refresh</button></div><section className="panel"><div className="filters">
    <Field label="Property search" type="search" placeholder="Property name" value={filters.q} onChange={e => change('q', e.target.value)}/>
    <Field label="Owner"><select value={filters.owner} onChange={e => change('owner', e.target.value)}><option value="">All owners</option>{owners.data?.map(o => <option value={o._id} key={o._id}>{o.name}</option>)}</select></Field>
    <Field label="Type"><select value={filters.type} onChange={e => change('type', e.target.value)}>{['', 'Villa', 'Hotel', 'Resort', 'Homestay', 'Cottage', 'Apartment', 'Bungalow'].map(t => <option key={t} value={t}>{t || 'All types'}</option>)}</select></Field>
    <Field label="Location" value={filters.location} onChange={e => change('location', e.target.value)} placeholder="Town or area"/>
    <Field label="Operational status"><select value={filters.operationalStatus} onChange={e => change('operationalStatus', e.target.value)}><option value="">Any status</option><option value="ready">Ready</option><option value="needs_attention">Needs attention</option></select></Field>
    <label className="checkbox"><input type="checkbox" checked={filters.arrivals === 'true'} onChange={e => change('arrivals', e.target.checked ? 'true' : '')}/>Arrivals today</label><label className="checkbox"><input type="checkbox" checked={filters.issues === 'true'} onChange={e => change('issues', e.target.checked ? 'true' : '')}/>Open issues</label>
  </div><Result state={state}>{state.data && (state.data.items.length ? <><Table headings={['Property / owner', 'Type / location', 'Today’s status', 'Occupied / rooms', 'Arrivals / departures', 'Open issues', 'Readiness', 'Assignment']}>{state.data.items.map(p => <tr key={p._id}><td><Link className="row-link" to={href('/properties/' + p._id)}>{p.name}</Link><small>{p.owner?.name}</small></td><td>{p.type}<small>{p.location}</small></td><td><Badge value={p.operationalStatus}/></td><td>{p.occupied} / {p.roomCount}</td><td>{p.checkIns} / {p.checkOuts}</td><td>{p.openIssues}</td><td>{p.pendingCleaning ? p.pendingCleaning + ' cleaning' : p.unavailableCount ? p.unavailableCount + ' unavailable' : 'Ready'}</td><td>You</td></tr>)}</Table><Pager data={state.data} setPage={setPage}/></> : <Empty title="No matching properties">Adjust your filters. Admin assignments appear here automatically.</Empty>)}</Result></section></>;
}
function PropertyDetail({ id }) {
  const state = useData(() => propertyService.get(id), 'property:' + id); const [tab, setTab] = useState('rooms'); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function perform(fn) { setBusy(true); setError(''); setMessage(''); try { await fn(); setMessage('Changes saved.'); state.reload(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <Result state={state}>{state.data && <><div className="page-head"><div><h1>{state.data.property.name}</h1><p>{state.data.property.owner?.name} · {state.data.property.type} · {state.data.property.location}</p></div><Badge value="BookMyVilla managed"/></div><div className="property-links">{['bookings', 'guests', 'housekeeping', 'requests', 'complaints', 'maintenance', 'inventory', 'damage', 'expenses', 'tasks', 'reports'].map(k => <Link key={k} to={'/' + k + '?propertyId=' + id}>{k === 'requests' ? 'Guest requests' : k.replace(/\b\w/g, c => c.toUpperCase())}</Link>)}</div><div className="tabs" role="tablist" aria-label="Property operations">{['rooms', 'calendar', 'staff', 'pricing'].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{t[0].toUpperCase() + t.slice(1)}</button>)}</div>{message && <p className="success" role="status">{message}</p>}{error && <p className="error" role="alert">{error}</p>}
    {tab === 'calendar' ? <Calendar id={id}/> : tab === 'staff' ? <Staff data={state.data} id={id} perform={perform} busy={busy}/> : tab === 'pricing' ? <section className="panel"><h2>Room pricing</h2><p>Base rate and extra guest rate per guest per night. Existing bookings retain their agreed rates.</p>{state.data.rooms.map(r => <Pricing key={r._id} room={r} perform={perform} busy={busy}/>)}</section> : <div className="room-grid">{state.data.rooms.length ? state.data.rooms.map(r => <section className="panel room" key={r._id}><div className="section-head"><h2>{r.number} · {r.name}</h2><Badge value={r.readinessStatus}/></div><p>{r.type} · Up to {r.capacity} guests</p>{r.readinessPercent !== null ? <div className="readiness"><strong>{r.readinessPercent}%</strong><span>Checklist readiness</span><progress max="100" value={r.readinessPercent}/></div> : <p>No completed readiness checklist recorded.</p>}{r.nextArrival && <p>Next arrival: {date(r.nextArrival.checkIn)} {r.nextArrival.guestDetails?.arrivalTime || ''}</p>}{r.pending.length > 0 && <p>Pending: {[...new Set(r.pending)].join(', ')}</p>}<Link to={'/housekeeping?propertyId=' + id}>Open cleaning & inspection</Link></section>) : <Empty title="No rooms configured">Ask Admin or listing staff to configure this property's units.</Empty>}</div>}
  </>}</Result>;
}
function Pricing({ room, perform, busy }) { const [base, setBase] = useState(room.baseRate); const [extra, setExtra] = useState(room.extraGuestRate ?? ''); return <form className="inline-form" onSubmit={e => { e.preventDefault(); perform(() => manager('/rooms/' + room._id + '/pricing', { method: 'PATCH', body: { baseRate: base, extraGuestRate: extra } })); }}><strong>{room.number} · {room.name}</strong><Field label="Base rate (INR / night)" type="number" min="0" step="1" required value={base} onChange={e => setBase(e.target.value)}/><Field label="Extra guest (INR / night)" type="number" min="0" step="1" placeholder="Quote required if unset" value={extra} onChange={e => setExtra(e.target.value)}/><button disabled={busy}>Save rates</button></form>; }
function Staff({ data, id, perform, busy }) {
  const [form, setForm] = useState({ name: '', role: 'housekeeping', phone: '' });
  return <section className="panel"><h2>Property staff</h2><form className="inline-form" onSubmit={e => { e.preventDefault(); perform(async () => { await api('/owner-ops/staff/' + id, { method: 'POST', body: form }); setForm({ name: '', role: 'housekeeping', phone: '' }); }); }}><Field label="Staff name" required maxLength="100" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))}/><Field label="Operational role"><select value={form.role} onChange={e => setForm(f => ({ ...f, role: e.target.value }))}>{['housekeeping', 'maintenance', 'caretaker', 'front_desk', 'manager'].map(r => <option key={r} value={r}>{r.replace(/_/g, ' ')}</option>)}</select></Field><Field label="Phone" type="tel" maxLength="20" value={form.phone} onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}/><button className="primary" disabled={busy}>Add staff</button></form>{data.staff.length ? <Table headings={['Staff', 'Role', 'Phone', 'Status', 'Action']}>{data.staff.map(s => <tr key={s._id}><td>{s.name}</td><td>{s.role}</td><td>{s.phone || '—'}</td><td><Badge value={s.active ? 'active' : 'inactive'}/></td><td><button disabled={busy} onClick={() => perform(() => api('/owner-ops/staff-member/' + s._id, { method: 'PATCH', body: { active: !s.active } }))}>{s.active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</Table> : <Empty title="Add your operational team">Staff assigned here can receive property tasks and guest requests.</Empty>}</section>;
}
function Calendar({ id }) {
  const [start, setStart] = useState(today()); const [end, setEnd] = useState(nextDay(today(), 7)); const [room, setRoom] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const state = useData(() => availabilityService.calendar(id, start, end), 'calendar:' + id + ':' + start + ':' + end);
  async function act(fn) { setBusy(true); setError(''); setMessage(''); try { await fn(); state.reload(); setMessage('Room availability updated.'); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <><div className="page-head"><div><h1>Room calendar</h1><p>Availability and readiness come directly from BookMyVilla.</p></div><button onClick={state.reload}>Refresh</button></div><section className="panel"><div className="filters"><Field label="From" type="date" value={start} onChange={e => setStart(e.target.value)} required/><Field label="Until (exclusive)" type="date" value={end} onChange={e => setEnd(e.target.value)} required/></div>{error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}<Result state={state}>{state.data && <>{state.data.rooms.length ? <><Table headings={['Room', ...state.data.dates.map(d => date(d))]}>{state.data.rooms.map(r => <tr key={r._id}><td><strong>{r.number}</strong><small>{r.name}</small></td>{r.days.map(d => <td key={d.date}><Badge value={d.status}/>{d.blockReference && <button className="text-btn" disabled={busy} onClick={() => act(() => availabilityService.unblock(d.blockReference))}>Unblock</button>}</td>)}</tr>)}</Table><form className="inline-form" onSubmit={e => { e.preventDefault(); act(() => availabilityService.block(room, { start, end, reason })); }}><Field label="Room to block"><select required value={room} onChange={e => setRoom(e.target.value)}><option value="">Choose room</option>{state.data.rooms.map(r => <option key={r._id} value={r._id}>{r.number} · {r.name}</option>)}</select></Field><Field label="Block reason" value={reason} maxLength="200" required onChange={e => setReason(e.target.value)} placeholder="Reason for blocking dates"/><button disabled={busy}>Block selected range</button></form></> : <Empty title="No rooms configured"/>}</>}</Result></section></>;
}
