import { useCallback, useState } from 'react';
import { Result, useData, usePanel } from './App';
import { housekeepingService, manager, propertyService, query, requestService, taskService } from './services/api';
import { Badge, date, Drawer, Empty, Field, guest, label, money, nextDay, Pager, PhotoField, Table, today } from './ui';
const titles = { housekeeping: 'Housekeeping & inspection', requests: 'Guest requests', complaints: 'Complaints', maintenance: 'Maintenance', inventory: 'Operational inventory', tasks: 'Operational tasks', damage: 'Damage reports', expenses: 'Operational expenses' };
export default function Queues({ kind }) { return kind === 'reports' ? <Reports/> : <Queue key={kind} kind={kind}/>; }
function Queue({ kind }) {
  const { propertyId } = usePanel(); const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null);
  const state = useData(() => manager('/resources/' + kind + '?' + query({ propertyId, page, status, q: search })), kind + ':' + propertyId + ':' + page + ':' + status + ':' + search);
  const close = useCallback(() => setEditing(null), []); const request = ['requests', 'complaints'].includes(kind);
  const statuses = request ? ['open', 'acknowledged', 'in_progress', 'completed', 'declined', 'cancelled'] : kind === 'housekeeping' ? ['open', 'in_progress', 'done'] : kind === 'inventory' ? ['In Stock', 'Low Stock', 'Out of Stock'] : kind === 'expenses' ? [] : ['open', 'in_progress', 'resolved', 'verified'];
  return <><div className="page-head"><div><h1>{titles[kind]}</h1><p>{{ housekeeping: 'Clean, inspect and release rooms using the shared readiness workflow.', requests: 'Customer requests from the same guest-facing stay records.', complaints: 'Assign ownership and keep guests informed as issues are resolved.', maintenance: 'Serious room issues block customer availability until verified.', inventory: 'Track property stock and request replenishment.', tasks: 'Assigned work, deadlines and evidence for your operations team.', damage: 'Record damage evidence and estimates for owner or finance review.', expenses: 'Submit property expenses for review. Approval remains with owner or finance.' }[kind]}</p></div><div className="actions"><button onClick={state.reload}>Refresh</button>{!request && <button className="primary" disabled={propertyId === 'all'} onClick={() => setEditing({ _new: true, property: { _id: propertyId } })}>{kind === 'housekeeping' ? 'Create cleaning task' : kind === 'inventory' ? 'Add stock item' : kind === 'expenses' ? 'Submit expense' : kind === 'damage' ? 'Report damage' : 'Create ' + (kind === 'maintenance' ? 'issue' : 'task')}</button>}</div></div>{!request && propertyId === 'all' && <p className="help">Select a working property above to create an entry.</p>}
    <section className="panel"><div className="filters"><Field label="Queue search" type="search" placeholder="Search this queue" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/>{statuses.length > 0 && <Field label="Status"><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{statuses.map(s => <option key={s} value={s}>{label(s)}</option>)}</select></Field>}</div><Result state={state}>{state.data && (state.data.items.length ? <><Table headings={kind === 'inventory' ? ['Item / property', 'Category', 'Current / minimum', 'Stock status', 'Action'] : kind === 'expenses' ? ['Description / property', 'Category / date', 'Amount', 'Approval', 'Action'] : request ? ['Guest / request', 'Property / room', 'Category / priority', 'Assigned staff', 'Opened', 'Status', 'Action'] : ['Task / property', 'Room / dates', 'Assignee', 'Priority', 'Status', 'Action']}>
      {state.data.items.map(r => <QueueRow key={r._id} record={r} kind={kind} edit={() => setEditing(r)}/>)}</Table><Pager data={state.data} setPage={setPage}/></> : <Empty title={'No ' + (kind === 'requests' ? 'guest requests' : kind) + ' in this view'}>Change filters or check again when new activity arrives.</Empty>)}</Result></section>
    {editing && <Drawer title={editing._new ? titles[kind] + ' · New entry' : titles[kind] + ' · Details'} close={close}><Editor key={editing._id || 'new'} kind={kind} record={editing} saved={() => { close(); state.reload(); }}/></Drawer>}
  </>;
}
function QueueRow({ record: r, kind, edit }) {
  if (kind === 'inventory') return <tr><td><strong>{r.itemName}</strong><small>{r.propertyId?.name}</small></td><td>{r.category}</td><td>{r.quantity} / {r.minThreshold} {r.unit}</td><td><Badge value={r.status}/></td><td><button onClick={edit}>Update stock</button></td></tr>;
  if (kind === 'expenses') return <tr><td>{r.description}<small>{r.property?.name}</small></td><td>{label(r.category)}<small>{date(r.incurredOn)}</small></td><td>{money(r.amount)}</td><td><Badge value={r.approvalStatus}/></td><td><button onClick={edit}>View receipt</button></td></tr>;
  if (['requests', 'complaints'].includes(kind)) return <tr><td><strong>{guest(r.booking) || r.guestName}</strong><small>{r.code}</small></td><td>{r.property?.name}<small>{r.booking?.room?.number || 'Unassigned'}</small></td><td>{label(r.category)}<small>{label(r.priority)}</small></td><td>{r.assignedStaff?.name || 'Unassigned'}</td><td>{date(r.createdAt)}</td><td><Badge value={r.status}/></td><td><button onClick={edit}>Assign / update</button></td></tr>;
  return <tr><td><strong>{r.title}</strong><small>{r.property?.name}</small></td><td>{r.room?.number || 'Property-wide'}<small>Due {date(r.dueDate)}{r.booking?.actualCheckOut ? ' · Checkout ' + date(r.booking.actualCheckOut) : ''}</small></td><td>{r.assignedStaff?.name || 'Unassigned'}</td><td><Badge value={r.priority}/></td><td><Badge value={kind === 'housekeeping' ? (r.status === 'done' ? 'ready' : r.stage) : r.status}/></td><td><button onClick={edit}>Open task</button></td></tr>;
}
function Editor({ kind, record, saved }) {
  const { checklist } = usePanel(); const propertyId = record.property?._id || record.property || record.propertyId?._id; const property = useData(() => propertyService.get(propertyId), 'editor-property:' + propertyId);
  const [form, setForm] = useState({ title: record.title || '', notes: record.notes || '', category: record.category || (kind === 'housekeeping' ? 'cleaning' : kind === 'inventory' ? 'Toiletries' : kind === 'expenses' ? 'maintenance' : 'other'), roomId: record.room?._id || '', assignedStaffId: record.assignedStaff?._id || '', dueDate: record.dueDate || today(), priority: record.priority || 'normal', severity: record.severity || 'minor', escalated: Boolean(record.escalated), stage: record.stage || 'dirty', status: record.status || 'open', checklist: record.checklist || [], photos: record.photos || [], estimatedAmount: record.estimatedAmount ?? '', quantity: record.quantity ?? 0, minThreshold: record.minThreshold ?? 5, itemName: record.itemName || '', unit: record.unit || 'Units', incurredOn: record.incurredOn || today(), amount: record.amount || '', description: record.description || '', receipt: record.receipt || '', note: '', eta: record.eta || '' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const set = (key, value) => setForm(f => ({ ...f, [key]: value })); const isRequest = ['requests', 'complaints'].includes(kind); const readOnly = !record._new && (kind === 'expenses' || (isRequest && ['completed', 'declined', 'cancelled'].includes(record.status)));
  async function submit(e) {
    e.preventDefault(); setBusy(true); setError('');
    try {
      if (record._new) {
        if (kind === 'housekeeping') await housekeepingService.create({ ...form, propertyId });
        else if (kind === 'inventory') await manager('/inventory', { method: 'POST', body: { ...form, propertyId } });
        else if (kind === 'expenses') await manager('/expenses', { method: 'POST', body: { ...form, propertyId } });
        else await taskService.create({ ...form, propertyId, kind: kind === 'tasks' ? 'task' : kind });
      } else if (kind === 'housekeeping') await housekeepingService.update(record._id, { stage: form.stage, checklist: form.checklist, assignedStaffId: form.assignedStaffId, notes: form.notes, photos: form.photos, priority: form.priority });
      else if (isRequest) await requestService.update(record._id, { status: form.status, note: form.note, eta: form.eta, escalated: form.escalated, ...(form.assignedStaffId && { assignedStaffId: form.assignedStaffId }) });
      else if (kind === 'inventory') await manager('/inventory/' + record._id, { method: 'PATCH', body: { quantity: form.quantity } });
      else await taskService.update(record._id, { status: form.status, assignedStaffId: form.assignedStaffId, notes: form.notes, photos: form.photos });
      saved();
    } catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  return <Result state={property}>{property.data && <form className="form-stack" onSubmit={submit}><p><strong>{property.data.property.name}</strong> · {record.code || record.title || 'New operational entry'}</p>{record.description && <p>{record.description}</p>}{error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}
    {kind === 'expenses' ? <><Field label="Description" required maxLength="200" disabled={readOnly} value={form.description} onChange={e => set('description', e.target.value)}/><Field label="Amount (INR)" type="number" min="1" step="1" required disabled={readOnly} value={form.amount} onChange={e => set('amount', e.target.value)}/><Field label="Incurred on" type="date" required disabled={readOnly} value={form.incurredOn} onChange={e => set('incurredOn', e.target.value)}/><Field label="Category"><select disabled={readOnly} value={form.category} onChange={e => set('category', e.target.value)}>{['housekeeping', 'maintenance', 'supplies', 'utilities', 'staff', 'other'].map(c => <option key={c}>{c}</option>)}</select></Field>{!readOnly && <PhotoField label="Receipt image" value={form.receipt ? [form.receipt] : []} onChange={v => set('receipt', v[0] || '')}/>}<p className="help">Submitted expenses are pending approval. This panel cannot approve expenses or deduct deposits.</p></> : kind === 'inventory' ? <>{record._new && <><Field label="Item name" required maxLength="100" value={form.itemName} onChange={e => set('itemName', e.target.value)}/><Field label="Category"><select value={form.category} onChange={e => set('category', e.target.value)}>{['Toiletries', 'Linen & Towels', 'Kitchen & Beverage', 'Cleaning Supplies', 'Maintenance Kits', 'Safety Equipment'].map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Unit" maxLength="40" value={form.unit} onChange={e => set('unit', e.target.value)}/><Field label="Minimum quantity" type="number" min="0" step="1" required value={form.minThreshold} onChange={e => set('minThreshold', e.target.value)}/></>}<Field label="Current quantity" type="number" min="0" step="1" required value={form.quantity} onChange={e => set('quantity', e.target.value)}/>{!record._new && <button type="button" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await taskService.create({ propertyId, title: 'Restock ' + record.itemName, kind: 'restock', dueDate: today(), notes: 'Current stock ' + record.quantity + ' ' + record.unit + '; minimum ' + record.minThreshold }); setMessage('Restock request created in Tasks.'); } catch (err) { setError(err.message); } finally { setBusy(false); } }}>Request restock</button>}</> : <>
      {record._new && <><Field label={kind === 'damage' ? 'Damaged item' : 'Task / issue title'} required maxLength="120" value={form.title} onChange={e => set('title', e.target.value)}/><div className="form-grid"><Field label="Room / unit"><select required={kind === 'housekeeping'} value={form.roomId} onChange={e => set('roomId', e.target.value)}><option value="">Property-wide</option>{property.data.rooms.map(r => <option key={r._id} value={r._id}>{r.number} · {r.name}</option>)}</select></Field><Field label="Due date" type="date" required value={form.dueDate} onChange={e => set('dueDate', e.target.value)}/></div>{kind === 'maintenance' && <><Field label="Issue category"><select value={form.category} onChange={e => set('category', e.target.value)}>{['other', 'ac', 'electricity', 'plumbing', 'water', 'wifi', 'pool', 'furniture', 'appliance', 'door_lock', 'generator'].map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Room impact"><select value={form.severity} onChange={e => set('severity', e.target.value)}><option value="minor">Minor — room remains bookable</option><option value="maintenance">Maintenance — block availability</option><option value="out_of_order">Out of order — block availability</option></select></Field></>}{kind === 'housekeeping' && <Field label="Task category"><select value={form.category} onChange={e => set('category', e.target.value)}>{['cleaning', 'turnover', 'inspection'].map(c => <option key={c}>{c}</option>)}</select></Field>}{kind === 'damage' && <Field label="Estimated damage amount (INR)" type="number" min="0" step="1" value={form.estimatedAmount} onChange={e => set('estimatedAmount', e.target.value)}/>}</>}
      {!readOnly && <Field label="Assigned operational staff"><select value={form.assignedStaffId} onChange={e => set('assignedStaffId', e.target.value)}><option value="">Unassigned</option>{property.data.staff.filter(s => s.active).map(s => <option key={s._id} value={s._id}>{s.name} · {s.role}</option>)}</select></Field>}
      {!record._new && !readOnly && <Field label={kind === 'housekeeping' ? 'Readiness stage' : 'Update status'}><select value={kind === 'housekeeping' ? form.stage : form.status} onChange={e => set(kind === 'housekeeping' ? 'stage' : 'status', e.target.value)}>{(kind === 'housekeeping' ? ['dirty', 'cleaning', 'inspection', 'ready'] : isRequest ? ['open', 'acknowledged', 'in_progress', 'completed', 'declined'] : ['open', 'in_progress', 'resolved', 'verified']).map(s => <option key={s} value={s}>{label(s)}</option>)}</select></Field>}
      {!readOnly && (isRequest ? <><Field label="Message to guest"><textarea maxLength="500" value={form.note} onChange={e => set('note', e.target.value)}/></Field><Field label="Expected completion" maxLength="80" value={form.eta} onChange={e => set('eta', e.target.value)}/><label className="checkbox"><input type="checkbox" checked={form.escalated} onChange={e => set('escalated', e.target.checked)}/>Escalate to Admin</label><p className="help">The guest sees this update in My Stay.</p></> : <><Field label="Operational notes / description"><textarea maxLength={kind === 'housekeeping' ? 500 : 1000} required={kind === 'damage'} value={form.notes} onChange={e => set('notes', e.target.value)}/></Field>{(record._new || kind === 'housekeeping') && <Field label="Priority"><select value={form.priority} onChange={e => set('priority', e.target.value)}><option value="normal">Normal</option><option value="high">High</option></select></Field>}{kind === 'housekeeping' && !record._new && <fieldset className="checklist"><legend>Readiness checklist</legend>{checklist.map(c => <label className="checkbox" key={c}><input type="checkbox" checked={form.checklist.includes(c)} onChange={e => set('checklist', e.target.checked ? [...form.checklist, c] : form.checklist.filter(v => v !== c))}/>{c}</label>)}<p className="help">Complete every check, submit for inspection, then verify Ready.</p></fieldset>}<PhotoField value={form.photos} onChange={v => set('photos', v)}/></>)}
      {kind === 'damage' && <p className="help">Damage estimates are for review. No deposit deduction or refund action is performed.</p>}
    </>}
    {(record.photos || (record.receipt ? [record.receipt] : [])).length > 0 && <div className="evidence">{(record.photos || [record.receipt]).filter(Boolean).map((p, i) => <a href={p} key={i} target="_blank" rel="noreferrer"><img src={p} alt={'Operational evidence ' + (i + 1)}/></a>)}</div>}
    {record.updates?.length > 0 && <section className="detail-section"><h3>Guest update history</h3>{record.updates.map((u, i) => <div className="activity" key={i}><Badge value={u.status}/><p>{u.note || 'Status updated'}</p><small>{date(u.at)} · {label(u.byRole)}</small></div>)}</section>}
    {!readOnly && <button className="primary" disabled={busy}>{busy ? 'Saving…' : record._new ? 'Create entry' : 'Save update'}</button>}
  </form>}</Result>;
}
function Reports() {
  const { propertyId } = usePanel(); const [start, setStart] = useState(nextDay(today(), -30)); const [end, setEnd] = useState(nextDay(today(), 1));
  const state = useData(() => manager('/reports?' + query({ propertyId, start, end })), 'reports:' + propertyId + ':' + start + ':' + end);
  return <><div className="page-head"><div><h1>Operational reports</h1><p>Completed cleaning, guest stays and issue resolution in the selected period.</p></div><button onClick={state.reload}>Refresh report</button></div><section className="panel"><div className="filters"><Field label="From" type="date" value={start} onChange={e => setStart(e.target.value)}/><Field label="Until (exclusive)" type="date" value={end} onChange={e => setEnd(e.target.value)}/></div><Result state={state}>{state.data && <><p className="report-total"><strong>{state.data.cleaning}</strong> cleaning tasks completed</p><h2>Guest stays</h2>{state.data.stays.length ? <Table headings={['Stay status', 'Bookings', 'Guests']}>{state.data.stays.map(r => <tr key={r._id}><td><Badge value={r._id}/></td><td>{r.count}</td><td>{r.guests}</td></tr>)}</Table> : <Empty title="No checked-in stays in this period"/>}<h2>Requests & operational work</h2>{[...state.data.requests, ...state.data.tasks].length ? <Table headings={['Work type', 'Status', 'Count']}>{[...state.data.requests, ...state.data.tasks].map((r, i) => <tr key={i}><td>{label(r._id.kind)}</td><td><Badge value={r._id.status}/></td><td>{r.count}</td></tr>)}</Table> : <Empty title="No operational work recorded in this period"/>}</>}</Result></section></>;
}
