import { useEffect, useState } from 'react';
export const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
export const nextDay = (day, offset) => new Date(Date.parse(day + 'T12:00:00Z') + offset * 86400000).toISOString().slice(0, 10);
export const label = value => String(value || '—').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
export const date = value => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', timeZone: 'Asia/Kolkata' }).format(new Date(value)) : '—';
export const guest = booking => booking?.guest?.name || booking?.user?.name || 'Guest';
export const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
export function Icon({ name = 'grid' }) {
  const paths = { grid: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z', calendar: 'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16', home: 'M3 11l9-8 9 8 M5 10v11h14V10 M9 21v-7h6v7', people: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M17 4a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-4 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0', list: 'M9 5h12 M9 12h12 M9 19h12 M3 5h1 M3 12h1 M3 19h1', check: 'M4 12l5 5L20 6', tools: 'M14 4a6 6 0 0 0-7 7L3 18l3 3 7-7a6 6 0 0 0 7-7l-4 4-4-4 4-4', bell: 'M5 16V9a7 7 0 0 1 14 0v7l2 3H3z M10 22h4', menu: 'M3 6h18 M3 12h18 M3 18h18', arrow: 'M4 12h16 M14 6l6 6-6 6', close: 'M5 5l14 14 M19 5L5 19', exit: 'M9 4H3v16h6 M10 12h11 M16 7l5 5-5 5', shield: 'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6', search: 'M16 16l5 5 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0', box: 'M3 7l9-4 9 4v10l-9 4-9-4z M3 7l9 4 9-4 M12 11v10' };
  return <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.list}/></svg>;
}
export function Badge({ value }) { return <span className={'badge tone-' + String(value || '').toLowerCase().replace(/\s/g, '_')}>{label(value)}</span>; }
export function Field({ label: title, children, ...props }) { return <label className="field"><span>{title}</span>{children || <input {...props}/>}</label>; }
export function Empty({ title = 'Nothing here yet', children }) { return <div className="empty"><Icon name="check"/><h3>{title}</h3><p>{children || 'New activity will appear here as your team works.'}</p></div>; }
export function Table({ headings, children }) { return <div className="table-wrap" tabIndex="0" aria-label="Scrollable operations table"><table><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
export function Pager({ data, setPage }) { return data.total > data.limit ? <div className="pager"><span>{(data.page - 1) * data.limit + 1}–{Math.min(data.page * data.limit, data.total)} of {data.total}</span><button disabled={data.page <= 1} onClick={() => setPage(data.page - 1)}>Previous</button><button disabled={data.page * data.limit >= data.total} onClick={() => setPage(data.page + 1)}>Next</button></div> : null; }
export function Drawer({ title, close, children }) {
  useEffect(() => { const handler = e => { if (e.key === 'Escape') close(); }; document.addEventListener('keydown', handler); const before = document.activeElement; const dialog = document.querySelector('.drawer'); dialog?.focus(); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', handler); document.body.style.overflow = ''; before?.focus(); }; }, [close]);
  function trap(e) { if (e.key !== 'Tab') return; const nodes = [...e.currentTarget.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea,a[href]')]; const first = nodes[0]; const last = nodes.at(-1); if (e.shiftKey && (document.activeElement === first || document.activeElement === e.currentTarget)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }
  return <div className="overlay"><button className="scrim" aria-label="Close details" onClick={close}/><section className="drawer" role="dialog" aria-modal="true" aria-label={title} tabIndex="-1" onKeyDown={trap}><header><h2>{title}</h2><button className="icon-btn" aria-label="Close details" onClick={close}><Icon name="close"/></button></header>{children}</section></div>;
}
export function PhotoField({ value = [], onChange, label: title = 'Evidence photos' }) {
  const [error, setError] = useState('');
  async function upload(e) { try { const files = [...e.target.files]; if (files.length > 3 || files.some(f => f.size > 1400000 || !['image/jpeg', 'image/png', 'image/webp'].includes(f.type))) throw new Error('Choose up to three JPG, PNG or WebP files under 1.4 MB each.'); const data = await Promise.all(files.map(f => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(f); }))); onChange(data); setError(''); } catch (err) { setError(err.message); } }
  return <div><Field label={title} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={upload}/><small>{value.length} photo(s) selected</small>{error && <p role="alert">{error}</p>}</div>;
}
