apiVersion: v1
kind: Service
metadata:
  name: owner
  labels:
    app.kubernetes.io/name: owner
    app.kubernetes.io/part-of: bookmyvilla
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: owner
  ports:
    - name: http
      port: 80
      targetPort: http
