import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useBlocker, useParams } from 'react-router-dom';
import { entryApi } from './api';
import { useAuth } from './App';
import { Alert, Badge, date, Field, Icon, Loading } from './ui';
import Media from './Media';
import Rooms from './Rooms';
const SECTIONS = [['basic', 'Basic information'], ['location', 'Location'], ['details', 'Property details'], ['amenities', 'Amenities'], ['rooms', 'Rooms / units'], ['media', 'Photos & media'], ['content', 'Content & nearby'], ['policies', 'Property policies'], ['pricing', 'Listing pricing']];
export default function Editor() {
  const { id, section: routeSection } = useParams(); const { data: meta } = useAuth();
  const [data, setData] = useState(null), [draft, setDraft] = useState(null), [error, setError] = useState(''), [fatal, setFatal] = useState(null), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false), [progress, setProgress] = useState(null), [section, setSection] = useState(['rooms', 'media'].includes(routeSection) ? routeSection : 'basic');
  const stateRef = useRef({}); stateRef.current = { dirty, busy, data };
  const blocker = useBlocker(({ currentLocation, nextLocation }) => dirty && !nextLocation.pathname.startsWith(`/properties/${id}`) && currentLocation.pathname !== nextLocation.pathname);
  useEffect(() => { if (blocker.state === 'blocked') { if (window.confirm('You have unsaved listing changes. Leave without saving?')) blocker.proceed(); else blocker.reset(); } }, [blocker]);
  useEffect(() => { const warning = e => { if (dirty) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', warning); return () => window.removeEventListener('beforeunload', warning); }, [dirty]);
  const accept = useCallback(v => { setData(v); setDraft(v.draft); setDirty(false); setFatal(null); }, []);
  useEffect(() => {
    const c = new AbortController(); setData(null); setDraft(null); setError(''); setFatal(null); setDirty(false);
    entryApi.get(id, c.signal).then(accept).catch(e => { if (e.name !== 'AbortError') setFatal(e); });
    return () => c.abort();
  }, [id, accept]);
  useEffect(() => { setSection(['rooms', 'media'].includes(routeSection) ? routeSection : 'basic'); }, [routeSection]);
  useEffect(() => {
    const c = new AbortController();
    const refresh = async () => {
      if (stateRef.current.busy) return;
      try { const fresh = await entryApi.get(id, c.signal); if (!stateRef.current.dirty) accept(fresh); else if (fresh.revision !== stateRef.current.data?.revision) setError('Admin or another session changed this listing. Copy any unsaved work, then reload to continue.'); }
      catch (e) { if ([403, 404].includes(e.status)) { setFatal(e); setData(null); } else if (e.name !== 'AbortError') setError(e.message); }
    };
    window.addEventListener('focus', refresh); return () => { c.abort(); window.removeEventListener('focus', refresh); };
  }, [id, accept]);
  const readOnly = !data?.permissions.edit || !routeSection;
  const change = value => { setDraft(value); setDirty(true); setNotice(''); setError(''); };
  const root = (key, value) => change({ ...draft, [key]: value });
  const detail = (key, value) => change({ ...draft, details: { ...draft.details, [key]: value } });
  async function save(next = draft, uploading = false) {
    setBusy(true); setError(''); setNotice(''); if (uploading) setProgress(0);
    try { const v = await entryApi.save(id, next, data.revision, uploading ? setProgress : undefined); accept(v); setNotice(uploading ? 'Photos uploaded and draft saved.' : 'Draft saved. You can safely continue later.'); return v; }
    catch (e) { setError(e.message); if ([403, 404].includes(e.status)) setFatal(e); throw e; }
    finally { setBusy(false); setProgress(null); }
  }
  async function submit() {
    setBusy(true); setError(''); setNotice('');
    try { const v = await entryApi.submit(id, data.revision); accept(v); setNotice('Sent to Admin for review. This listing has not been published.'); }
    catch (e) { setError(e.message); if (e.data.checks) setData(v => ({ ...v, completion: { percent: e.data.percent, complete: false, checks: e.data.checks } })); if ([403, 404].includes(e.status)) setFatal(e); }
    finally { setBusy(false); }
  }
  if (fatal) return <section className="panel access-denied"><Icon name="lock" width="32" height="32" /><h1>{[403, 404].includes(fatal.status) ? 'Access denied' : 'Unable to load listing'}</h1><p>{[403, 404].includes(fatal.status) ? 'This property is not assigned to your account, or the assignment was removed. Contact Admin if you need access.' : fatal.message}</p><Link className="button ghost" to="/properties">Back to assigned properties</Link></section>;
  if (!data || !draft) return <Loading />;
  const d = draft.details || {};
  function input(label, key, options = {}) {
    const { required, type = 'text', maxLength = 160, min, max, hint, top } = options;
    const value = (top ? draft[key] : d[key]) ?? '';
    const invalid = key === 'pincode' && value && !/^\d{6}$/.test(value) ? 'Enter a six-digit pincode.' : type === 'number' && value !== '' && (Number(value) < min || Number(value) > max) ? `Enter a value between ${min} and ${max}.` : '';
    return <Field label={label} required={required} hint={hint} error={invalid}><input type={type} value={value} required={required} maxLength={maxLength} min={min} max={max} step={['latitude', 'longitude'].includes(key) ? 'any' : undefined} onChange={e => top ? root(key, e.target.value) : detail(key, e.target.value)} aria-invalid={Boolean(invalid)} /></Field>;
  }
  function area(label, key, maxLength, required, top = false) { return <Field label={label} required={required} hint={`${(top ? draft[key] : d[key])?.length || 0} / ${maxLength} characters`}><textarea value={(top ? draft[key] : d[key]) || ''} rows={key === 'description' ? 7 : 3} maxLength={maxLength} onChange={e => top ? root(key, e.target.value) : detail(key, e.target.value)} required={required} /></Field>; }
  const safeSave = (...args) => save(...args).catch(() => {});
  return <><Link className="breadcrumb" to="/properties">Assigned properties / {data.draft.name || 'Property listing'}</Link><div className="page-heading editor-heading"><div><h1>{draft.name || 'Property listing'}</h1><p>{draft.type} · {draft.location} · {data.managementMode === 'BOOKMYVILLA_MANAGED' ? 'Managed by BookMyVilla' : 'Self Managed'}</p></div><div className="button-row"><Badge value={data.dataStatus} />{readOnly && data.permissions.edit && <Link className="button primary" to={`/properties/${id}/edit`}>Edit data</Link>}</div></div>
    <Alert>{error}</Alert><Alert tone="success">{notice}</Alert>{data.reviewReason && <Alert tone="warning"><strong>Changes requested by Admin</strong><p>{data.reviewReason}</p></Alert>}
    {!data.permissions.edit && <Alert tone="info">{data.dataStatus === 'COMPLETED' ? 'Admin approved this listing. Ask Admin to request changes if further edits are needed.' : 'This listing is with Admin for review. You can view its information while waiting.'}</Alert>}
    <div className="editor-layout"><nav className="section-nav" aria-label="Listing sections">{SECTIONS.map(([key, label]) => <button key={key} type="button" aria-current={key === section ? 'step' : undefined} className={key === section ? 'active' : ''} onClick={() => setSection(key)}>{label}</button>)}</nav>
    <section className="panel editor-panel"><div className="panel-heading"><div><h2>{SECTIONS.find(([key]) => key === section)?.[1]}</h2><p>{readOnly ? 'Listing information · view only' : 'Required fields are marked with an asterisk.'}</p></div></div><form noValidate onSubmit={e => { e.preventDefault(); if (!readOnly) safeSave(); }}><fieldset disabled={readOnly || busy}>
      {section === 'basic' && <div className="stack"><div className="form-grid">{input('Property name', 'name', { required: true, top: true })}<Field label="Property type" required><select value={draft.type} onChange={e => root('type', e.target.value)}>{meta.propertyTypes.map(t => <option key={t}>{t}</option>)}</select></Field><Field label="Owner reference" hint="Linked by Admin; cannot be changed here."><input value={data.owner?.name || 'Owner reference unavailable'} readOnly /></Field></div>{area('Short description', 'shortDescription', 250, true)}{area('Full description', 'description', 5000, true)}</div>}
      {section === 'location' && <div className="stack">{area('Address', 'address', 500, true)}<div className="form-grid">{input('City', 'city', { required: true, maxLength: 80 })}{input('State', 'state', { required: true, maxLength: 80 })}{input('Pincode', 'pincode', { required: true, maxLength: 6 })}{input('Listing location', 'location', { required: true, top: true })}{input('Landmark', 'landmark', { maxLength: 200 })}{input('Map link', 'mapLink', { required: true, top: true, type: 'url', maxLength: 2048 })}{input('Latitude', 'latitude', { type: 'number', min: -90, max: 90 })}{input('Longitude', 'longitude', { type: 'number', min: -180, max: 180 })}</div></div>}
      {section === 'details' && <div className="stack"><p className="muted">{['Villa', 'Apartment', 'Homestay', 'Cottage'].includes(draft.type) ? 'Add details for the entire property. Describe its private facilities and sleeping capacity.' : 'Add the accommodation count and describe rooms, cottages and shared facilities.'}</p><div className="form-grid">{input('Guest capacity', 'guestCapacity', { type: 'number', min: 1, max: 500, required: true })}{input('Bedrooms', 'bedrooms', { type: 'number', min: 0, max: 200, required: !['Hotel', 'Resort'].includes(draft.type) })}{input('Bathrooms', 'bathrooms', { type: 'number', min: 0, max: 200, required: true })}{input('Floors', 'floors', { type: 'number', min: 0, max: 100 })}{['Hotel', 'Resort'].includes(draft.type) && input('Total rooms / units', 'totalRooms', { type: 'number', min: 1, max: 1000, required: true })}</div>{['Villa', 'Cottage', 'Homestay'].includes(draft.type) && area('Caretaker listing information', 'caretakerInfo', 500, false)}{draft.type === 'Resort' && <Field label="Activities / common facilities" hint="One facility per line."><textarea value={(draft.facilities || []).join('\n')} onChange={e => root('facilities', e.target.value.split('\n'))} rows={4} /></Field>}</div>}
      {section === 'amenities' && <div className="stack"><p className="muted">Select amenities actually provided by this property.</p><div className="amenity-grid">{[...new Set([...meta.amenities, ...draft.amenities])].map(a => <label key={a}><input type="checkbox" checked={draft.amenities.includes(a)} onChange={e => root('amenities', e.target.checked ? [...draft.amenities, a] : draft.amenities.filter(v => v !== a))} />{a}</label>)}</div><Field label="Additional listing amenities" hint="One additional amenity per line. Existing standardized options are listed above."><textarea rows={3} value={draft.amenities.filter(a => !meta.amenities.includes(a)).join('\n')} onChange={e => root('amenities', [...draft.amenities.filter(a => meta.amenities.includes(a)), ...e.target.value.split('\n')])} /></Field></div>}
      {section === 'rooms' && <Rooms key={id} draft={draft} data={data} meta={meta} readOnly={readOnly} busy={busy} onChange={change} onSave={safeSave} setError={setError} onProcessing={setBusy} />}
      {section === 'media' && <div className="stack"><Media photos={draft.photos} categories={draft.photoCategories} categoryOptions={meta.photoCategories} readOnly={readOnly} busy={busy} setError={setError} onProcessing={setBusy} onChange={(photos, photoCategories) => change({ ...draft, photos, photoCategories })} onUpload={async (photos, photoCategories) => { const next = { ...draft, photos, photoCategories }; change(next); await save(next, true); }} /><Field label="Video links" hint="Optional video links, one per line."><textarea rows={3} value={(draft.videos || []).join('\n')} onChange={e => root('videos', e.target.value.split('\n').filter(Boolean))} /></Field></div>}
      {section === 'content' && <div className="stack"><Field label="Property highlights" hint="One highlight per line, up to 12."><textarea value={(d.highlights || []).join('\n')} rows={4} onChange={e => detail('highlights', e.target.value.split('\n'))} /></Field>{area('Arrival instructions', 'arrivalInstructions', 1000, false)}<h3>Nearby places</h3>{(d.nearbyPlaces || []).map((place, i) => <div className="nearby-row" key={i}><Field label="Place name"><input value={place.name} maxLength={120} onChange={e => detail('nearbyPlaces', d.nearbyPlaces.map((p, n) => n === i ? { ...p, name: e.target.value } : p))} /></Field><Field label="Category"><select value={place.category} onChange={e => detail('nearbyPlaces', d.nearbyPlaces.map((p, n) => n === i ? { ...p, category: e.target.value } : p))}>{['Attraction', 'Restaurant', 'Hospital', 'Fuel Station', 'Transport'].map(c => <option key={c}>{c}</option>)}</select></Field>{['distanceKm', 'travelMinutes'].map(key => <Field key={key} label={key === 'distanceKm' ? 'Distance (km)' : 'Travel (minutes)'}><input type="number" min="0" step="any" value={place[key]} onChange={e => detail('nearbyPlaces', d.nearbyPlaces.map((p, n) => n === i ? { ...p, [key]: e.target.value } : p))} /></Field>)}{!readOnly && <button className="text-button danger" type="button" onClick={() => detail('nearbyPlaces', d.nearbyPlaces.filter((_, n) => n !== i))}>Remove</button>}</div>)}{!readOnly && <button type="button" className="button ghost" disabled={(d.nearbyPlaces?.length || 0) >= 20} onClick={() => detail('nearbyPlaces', [...(d.nearbyPlaces || []), { name: '', category: 'Attraction', distanceKm: '', travelMinutes: '' }])}>Add nearby place</button>}</div>}
      {section === 'policies' && <div className="stack"><div className="form-grid">{input('Check-in time', 'checkInTime', { type: 'time', required: true })}{input('Check-out time', 'checkOutTime', { type: 'time', required: true })}</div>{area('Pet policy', 'petPolicy', 300, true)}{area('Smoking policy', 'smokingPolicy', 300, true)}{area('Party policy', 'partyPolicy', 300, true)}{area('Child policy', 'childPolicy', 300, true)}<p className="muted">Only property-level listing policies can be entered here. Cancellation templates remain controlled by authorized staff.</p></div>}
    </fieldset>{section === 'pricing' && <div className="stack"><Field label="Authorized base listing rate"><input value={`₹${Number(data.pricing.baseRate || 0).toLocaleString('en-IN')} per night`} readOnly /></Field><p className="muted">Your Data Entry permission does not allow pricing edits. Ask Admin or authorized property staff to correct a missing rate before submission.</p></div>}</form></section>
    <aside className="completion-panel"><h2>Listing completeness</h2><div className="completion-head"><strong>{data.completion.percent}%</strong><span>of required checks</span></div><progress max="100" value={data.completion.percent} aria-label="Listing completeness" /><ul>{data.completion.checks.map(c => <li key={c.key}><span className={c.valid ? 'check-mark valid' : 'check-mark'}>{c.valid ? <Icon name="check" width="14" height="14" /> : <span />}</span><button type="button" onClick={() => setSection(c.key === 'pricing' ? 'pricing' : c.key)}>{c.label}</button></li>)}</ul><p className="muted">{dirty ? 'Unsaved changes. Save draft to update these checks.' : `Last saved ${date(data.updatedAt)}.`}</p><p className="muted">Review: <Badge value={data.status} /></p>{readOnly && <Link to="/review-status">Open review status</Link>}</aside></div>
    {!readOnly && <div className="save-bar"><div role="status">{progress !== null ? `Uploading ${progress}%…` : busy ? 'Saving to BookMyVilla…' : dirty ? 'Unsaved changes' : 'Draft is saved'}{progress !== null && <progress value={progress} max="100" aria-label="Photo upload progress" />}</div><div className="button-row"><button type="button" className="button ghost" disabled={busy} onClick={() => safeSave()}><Icon name="save" />Save draft</button><button type="button" className="button primary" disabled={busy || dirty || !data.completion.complete} title={dirty ? 'Save the draft before submitting.' : !data.completion.complete ? 'Complete the required sections first.' : undefined} onClick={submit}>{data.dataStatus === 'CHANGES_REQUIRED' ? 'Resubmit for review' : 'Submit for review'}<Icon name="arrow" /></button></div></div>}
  </>;
}
