import { useState } from 'react';
import { Field } from './ui';
import Media from './Media';
export default function Rooms({ draft, onChange, onSave, data, meta, readOnly, busy, setError, onProcessing }) {
  const [index, setIndex] = useState(null);
  const room = index === null ? null : draft.rooms[index];
  const change = (key, value) => onChange({ ...draft, rooms: draft.rooms.map((r, i) => i === index ? { ...r, [key]: value } : r) });
  const roomTypes = [...new Set(draft.rooms.map(r => r.type).filter(Boolean))];
  return <><p className="muted">Edit the existing villa booking unit. Describe individual bedrooms in Property details; new rooms cannot be added.</p><div className="room-list">{draft.rooms.map((r, i) => <button key={r._id || i} type="button" className={index === i ? 'selected' : ''} disabled={busy} onClick={() => setIndex(i)}><strong>{r.name || 'New room / unit'}</strong><span>{r.number || 'Number needed'} · {r.type || 'Type needed'} · {r.capacity || '—'} guests</span></button>)}</div>
  {room && <div className="room-editor"><h3>{room.name || 'New room / unit'}</h3><div className="form-grid"><Field label="Display name" required><input value={room.name} maxLength={80} onChange={e => change('name', e.target.value)} disabled={readOnly || busy} /></Field><Field label="Room / unit number" required hint="Unique within this property."><input value={room.number} maxLength={30} onChange={e => change('number', e.target.value)} disabled={readOnly || busy} /></Field><Field label="Room type" required hint="Choose an existing type or enter a new one."><input list="room-types" value={room.type} maxLength={60} onChange={e => change('type', e.target.value)} disabled={readOnly || busy} /><datalist id="room-types">{roomTypes.map(t => <option key={t}>{t}</option>)}</datalist></Field><Field label="Guest capacity" required><input type="number" min="1" max="50" value={room.capacity ?? ''} onChange={e => change('capacity', e.target.value === '' ? '' : Number(e.target.value))} disabled={readOnly || busy} /></Field><Field label="Bed type"><input value={room.bedType || ''} maxLength={60} onChange={e => change('bedType', e.target.value)} disabled={readOnly || busy} /></Field><Field label="View"><input value={room.view || ''} maxLength={80} onChange={e => change('view', e.target.value)} disabled={readOnly || busy} /></Field><Field label="Size (sq ft)"><input type="number" min="0" value={room.sizeSqFt ?? ''} onChange={e => change('sizeSqFt', e.target.value)} disabled={readOnly || busy} /></Field><Field label="Authorized base rate" hint="Rate entry is restricted to authorized property staff."><input value={room._id ? `₹${(data.roomRates[room._id] || 0).toLocaleString('en-IN')}` : `Uses authorized property rate: ₹${data.pricing.baseRate.toLocaleString('en-IN')}`} readOnly /></Field></div>
    <h3>Room amenities</h3><div className="amenity-grid">{[...new Set([...meta.amenities, ...room.amenities])].map(a => <label key={a}><input type="checkbox" checked={room.amenities.includes(a)} disabled={readOnly || busy} onChange={e => change('amenities', e.target.checked ? [...room.amenities, a] : room.amenities.filter(v => v !== a))} />{a}</label>)}</div>
    <h3>Room photos</h3><Media photos={room.photos} showCategories={false} onProcessing={onProcessing} categoryOptions={meta.photoCategories} readOnly={readOnly} busy={busy} setError={setError} onChange={photos => change('photos', photos)} onUpload={async photos => { const next = { ...draft, rooms: draft.rooms.map((r, i) => i === index ? { ...r, photos } : r) }; onChange(next); await onSave(next, true); }} />
    {!readOnly && <div className="button-row"><button type="button" className="button primary" disabled={busy} onClick={() => onSave(draft)}>Save room draft</button>{!room._id && <button type="button" className="button ghost danger" disabled={busy} onClick={() => { onChange({ ...draft, rooms: draft.rooms.filter((_, i) => i !== index) }); setIndex(null); }}>Remove new room</button>}</div>}
  </div>}</>;
}
