apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookmyvilla-uploads
  labels:
    app.kubernetes.io/name: uploads
    app.kubernetes.io/part-of: bookmyvilla
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
