#!/usr/bin/env node
// Generates docker-compose.yaml from backend/shared/serviceCatalog.js so the
// container list always matches the services the gateway routes to.
//   node infrastructure/scripts/generate-compose.js
const fs = require('fs');
const path = require('path');
const { SERVICES } = require('../../backend/shared/serviceCatalog');

const root = path.join(__dirname, '..', '..');
const healthcheck = port => [
  '    healthcheck:',
  `      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:${port}/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]`,
  '      interval: 20s', '      timeout: 5s', '      retries: 5', '      start_period: 40s'
];

const lines = [
  '# Generated by infrastructure/scripts/generate-compose.js from backend/shared/serviceCatalog.js.',
  '# Edit the catalog or the generator, then re-run it.',
  '#',
  '# Public backend entry: api-gateway on 127.0.0.1:2001 (host nginx -> api.bookmyvilla.online).',
  '# The 12 microservices, RabbitMQ and Redis are reachable only on the internal network.',
  '# Service-to-service /internal calls use INTERNAL_SERVICE_TOKEN from backend/.env.',
  'name: bookmyvilla',
  '',
  'x-backend: &backend',
  '  build:',
  '    context: ./backend',
  '    dockerfile: Dockerfile',
  '  image: bookmyvilla/backend:local',
  '  env_file:',
  '    - path: ./backend/.env',
  '      required: true',
  '  volumes:',
  '    - ./backend/uploads:/app/uploads',
  '  restart: unless-stopped',
  '  networks:',
  '    - bookmyvilla-network',
  '  depends_on:',
  '    - mongo',
  '    - rabbitmq',
  '    - redis',
  '',
  'x-backend-env: &backend-env',
  '  RABBITMQ_URL: amqp://rabbitmq:5672',
  '  REDIS_URL: redis://redis:6379',
  '',
  'services:',
  '  api-gateway:',
  '    <<: *backend',
  '    container_name: bookmyvilla-api-gateway',
  '    command: ["node", "api-gateway/src/server.js"]',
  '    ports:',
  '      - "127.0.0.1:2001:2001"',
  '    environment:',
  '      <<: *backend-env',
  '      SERVICE_NAME: api-gateway',
  '      PORT: "2001"',
  ...healthcheck(2001),
  ''
];

for (const [name, def] of Object.entries(SERVICES)) {
  lines.push(
    `  ${name}:`,
    '    <<: *backend',
    `    container_name: bookmyvilla-${name}`,
    `    command: ["node", "services/${name}/src/server.js"]`,
    '    environment:',
    '      <<: *backend-env',
    `      SERVICE_NAME: ${name}`,
    `      PORT: "${def.port}"`,
    // Independent services read <KEY>_MONGODB_URI / <KEY>_DB_NAME from backend/.env
    // (unset = the shared MONGODB_URI database, i.e. today's data).
    ...(def.database ? [`      # Own database: ${def.database.key}_MONGODB_URI / ${def.database.key}_DB_NAME in backend/.env (target: ${def.database.target})`] : []),
    ...(name === 'auth-service' ? [
      '      # TEMPORARY for live testing: the sign-up/login OTP is shown on screen',
      '      # instead of sent by SMS. Delete this line before real users sign up.',
      '      ALLOW_DEMO_OTP: "true"'
    ] : []),
    ...healthcheck(def.port),
    ''
  );
}

lines.push(
  '  rabbitmq:',
  '    image: rabbitmq:3.13-management-alpine',
  '    container_name: bookmyvilla-rabbitmq',
  '    restart: unless-stopped',
  '    ports:',
  '      - "127.0.0.1:15672:15672"   # management UI, local only',
  '    volumes:',
  '      - bookmyvilla-rabbitmq-data:/var/lib/rabbitmq',
  '    networks:',
  '      - bookmyvilla-network',
  '    healthcheck:',
  '      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]',
  '      interval: 20s', '      timeout: 10s', '      retries: 6', '      start_period: 40s',
  '',
  '  redis:',
  '    image: redis:7-alpine',
  '    container_name: bookmyvilla-redis',
  '    restart: unless-stopped',
  '    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]',
  '    networks:',
  '      - bookmyvilla-network',
  '    healthcheck:',
  '      test: ["CMD", "redis-cli", "ping"]',
  '      interval: 15s', '      timeout: 5s', '      retries: 5',
  '',
  '  mongo:',
  '    image: mongo:7',
  '    container_name: bookmyvilla-mongo',
  '    restart: unless-stopped',
  '    volumes:',
  '      - bookmyvilla-mongo-data:/data/db',
  '    networks:',
  '      - bookmyvilla-network',
  '    # mongosh is slow to cold-start on a loaded host; this only reports status.',
  '    healthcheck:',
  '      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand(\'ping\').ok"]',
  '      interval: 15s', '      timeout: 20s', '      retries: 10', '      start_period: 60s',
  ''
);

// Web apps (development containers; production serves static builds via nginx).
const webApps = [['frontend', 5173, 5173], ['admin', 5174, 5174], ['owner', 5175, 5175], ['caretaker', 5176, 5176], ['data-entry', 5178, 5176], ['villa-manager', 5177, 5177]];
for (const [app, hostPort, containerPort] of webApps) {
  lines.push(
    `  ${app}:`,
    '    build:',
    `      context: ./${app}`,
    '      dockerfile: Dockerfile',
    `    container_name: bookmyvilla-${app}`,
    '    ports:',
    `      - "${hostPort}:${containerPort}"`,
    '    environment:',
    '      VITE_API_BASE_URL: http://localhost:2001',
    '    depends_on:',
    '      - api-gateway',
    '    restart: unless-stopped',
    '    networks:',
    '      - bookmyvilla-network',
    ''
  );
}

lines.push(
  'networks:',
  '  bookmyvilla-network:',
  '    driver: bridge',
  '',
  'volumes:',
  '  bookmyvilla-mongo-data:',
  '  bookmyvilla-rabbitmq-data:',
  ''
);

fs.writeFileSync(path.join(root, 'docker-compose.yaml'), lines.join('\n'));
console.log('docker-compose.yaml written');
