apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  labels:
    app.kubernetes.io/name: pricing-service
    app.kubernetes.io/part-of: bookmyvilla
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pricing-service
  ports:
    - name: http
      port: 2106
      targetPort: http
